In [1]:
import pandas as pd

In [2]:
lists= ['홍길동','이순신','유관순','윤봉길']
series = pd.Series(lists)
type(series)

pandas.core.series.Series

In [3]:
series

0    홍길동
1    이순신
2    유관순
3    윤봉길
dtype: object

In [4]:
lists = (['홍길동',29,'여'],['이순신',24,'남'],
        ['유관순',38,'남'],['윤봉길',31,'여'])
df=pd.DataFrame(lists)
type(df)

pandas.core.frame.DataFrame

In [5]:
df

0   1  2
0  홍길동  29  여
1  이순신  24  남
2  유관순  38  남
3  윤봉길  31  여

In [6]:
df.index=['1번','2번','3번','4번']
df

0   1  2
1번  홍길동  29  여
2번  이순신  24  남
3번  유관순  38  남
4번  윤봉길  31  여

In [9]:
df.columns =['이름','나이','성별']
df

이름  나이 성별
1번  홍길동  29  여
2번  이순신  24  남
3번  유관순  38  남
4번  윤봉길  31  여

일부 열 값 뽑기

In [10]:
df['나이']

1번    29
2번    24
3번    38
4번    31
Name: 나이, dtype: int64

In [11]:
df[['나이','성별']]

나이 성별
1번  29  여
2번  24  남
3번  38  남
4번  31  여

일부 행 추출

In [15]:
df[1:3] #인덱스 순번 1부터 2까지 가져오기

이름  나이 성별
2번  이순신  24  남
3번  유관순  38  남

In [16]:
df['2번':'3번'] #행 이름에서 2번, 3번 데이터 가져오기

이름  나이 성별
2번  이순신  24  남
3번  유관순  38  남

sklearn 사용하기

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier #명목형 의사결정나무

numpy 함수 다루기

In [19]:
import numpy as np

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [23]:
np.array(range(20)) #0부터 20개 숫자 만들기

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
np.array(range(20)).reshape(4,5) #0부터 20개의 숫자로 4행 5열 만들기

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
data = {\
       '나이' : [20,23,49,38,32,29,25,30,32,26],\
       '성별' : ['남','여','남','여','여','여','여','여','남',np.nan] \
       }

In [31]:
data = pd.DataFrame(data)

In [32]:
data

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [33]:
type(data)

pandas.core.frame.DataFrame

In [34]:
data['나이']

0    20
1    23
2    49
3    38
4    32
5    29
6    25
7    30
8    32
9    26
Name: 나이, dtype: int64

In [35]:
data['나이'].sum() #나이 열의 합계 구하기 -1방법

304

In [36]:
sum(data['나이']) #나이 열의 합계 구하기 -2방법

304

In [37]:
data['나이'].max()

49

In [38]:
max(data['나이'])

49

In [39]:
data['나이'].min()

20

In [40]:
min(data['나이'])

20

In [41]:
data['나이'].mean()

30.4

In [43]:
data['나이'].median()

29.5

In [44]:
data['나이'].var()

69.15555555555557

In [45]:
data['나이'].std()

8.315981935740094

In [46]:
pow(data['나이'],3) #거듭제곱 구하기 나이 열의 세제곱값을 구하기

0      8000
1     12167
2    117649
3     54872
4     32768
5     24389
6     15625
7     27000
8     32768
9     17576
Name: 나이, dtype: int64

In [47]:
data.quantile(0.25) #1사분위수

나이    25.25
Name: 0.25, dtype: float64

In [48]:
data.quantile(0.5) #2사분위수

나이    29.5
Name: 0.5, dtype: float64

In [49]:
data.quantile(0.75) #3사분위수

나이    32.0
Name: 0.75, dtype: float64

In [50]:
data.quantile(1) #4사분위수

나이    49.0
Name: 1, dtype: float64

In [51]:
data['나이']/7

0    2.857143
1    3.285714
2    7.000000
3    5.428571
4    4.571429
5    4.142857
6    3.571429
7    4.285714
8    4.571429
9    3.714286
Name: 나이, dtype: float64

In [52]:
round(data['나이']/7)

0    3.0
1    3.0
2    7.0
3    5.0
4    5.0
5    4.0
6    4.0
7    4.0
8    5.0
9    4.0
Name: 나이, dtype: float64

In [53]:
round(data['나이']/7,2) #소수점 셋째자리에서 반올림

0    2.86
1    3.29
2    7.00
3    5.43
4    4.57
5    4.14
6    3.57
7    4.29
8    4.57
9    3.71
Name: 나이, dtype: float64

In [54]:
data.head()

나이 성별
0  20  남
1  23  여
2  49  남
3  38  여
4  32  여

In [55]:
data.tail()

나이   성별
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [56]:
data.columns #열 이름 가져오기

Index(['나이', '성별'], dtype='object')

In [57]:
data.index #data 변수의 행 이름을 가져오기 

RangeIndex(start=0, stop=10, step=1)

In [58]:
data['성별'].value_counts() #data변수에서 성별 열의 값 개수를 세기

여    6
남    3
Name: 성별, dtype: int64

In [59]:
data['성별'].unique() #중복값 제거

array(['남', '여', nan], dtype=object)

In [60]:
data.isnull() #결측값 여부 확인

나이     성별
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False
5  False  False
6  False  False
7  False  False
8  False  False
9  False   True

In [61]:
data['성별'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: 성별, dtype: bool

In [62]:
sum(data['성별'].isnull()) #결측치 개수 세기

1

In [63]:
data['성별'].isnull().sum()

1

In [64]:
data.count() #data 변수에서 열별 값의 개수 세기

나이    10
성별     9
dtype: int64

In [66]:
"I am superman!".count('a') #문자열에서 a 개수 세기

2

In [69]:
data.info() #데이터변수 정보 조회

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   나이      10 non-null     int64 
 1   성별      9 non-null      object
dtypes: int64(1), object(1)
memory usage: 288.0+ bytes


In [70]:
data.describe() #데이터 변수의 기초 통계량 구하기

나이
count  10.000000
mean   30.400000
std     8.315982
min    20.000000
25%    25.250000
50%    29.500000
75%    32.000000
max    49.000000

In [71]:
data # 10행 2열 데이터 확인

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [72]:
data.transpose() # 2행 10열의 데이터로 바꾸기 1방법

0   1   2   3   4   5   6   7   8    9
나이  20  23  49  38  32  29  25  30  32   26
성별   남   여   남   여   여   여   여   여   남  NaN

In [73]:
data.T #2행 10열 데이터로 바꾸기 2방법

0   1   2   3   4   5   6   7   8    9
나이  20  23  49  38  32  29  25  30  32   26
성별   남   여   남   여   여   여   여   여   남  NaN

In [74]:
data

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [75]:
data.loc[3] #data 의 3행의 값을 확인하기

나이    38
성별     여
Name: 3, dtype: object

In [76]:
data.loc[3:7] #data의 3행부터 7행까지 값확인

나이 성별
3  38  여
4  32  여
5  29  여
6  25  여
7  30  여

In [78]:
data.loc[:,'성별'] #data 변수의 성별 열 값 가져오기

0      남
1      여
2      남
3      여
4      여
5      여
6      여
7      여
8      남
9    NaN
Name: 성별, dtype: object

In [79]:
data.loc[:,['나이','성별']] #data변수의 나이와 성별 열 값을 가져오기

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [80]:
data.loc[3:7,'성별'] #data변수에서 3-7행과 성별 열값을 가져오기

3    여
4    여
5    여
6    여
7    여
Name: 성별, dtype: object

In [81]:
data['성별']=='남' #data 변수의 성별 열 값이 남과 같은지 물어보기

0     True
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8     True
9    False
Name: 성별, dtype: bool

In [83]:
data.loc[data['성별']=='남'] #성별 열 값이 남인 true의 실제값 가져오기

나이 성별
0  20  남
2  49  남
8  32  남

In [84]:
data

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [85]:
data.iloc[3] #행위치가 3인 값 가져오기

나이    38
성별     여
Name: 3, dtype: object

In [86]:
data.iloc[4:8] #행위치가 4부터 7까지의 값을 가져오기

나이 성별
4  32  여
5  29  여
6  25  여
7  30  여

In [87]:
data.iloc[:,1] #열 위치가 1인 값을 가져오기

0      남
1      여
2      남
3      여
4      여
5      여
6      여
7      여
8      남
9    NaN
Name: 성별, dtype: object

In [88]:
data.iloc[:,0:2] # 열위치 0부터 1까지 값을 가져오기

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [89]:
data.iloc[2,1] #행 위치 2, 열위치 1 데이터 가져오기

'남'

In [90]:
data.iloc[3:7,1] #행위치는 3부터 6, 열위치 1 데이터 가져오기

3    여
4    여
5    여
6    여
Name: 성별, dtype: object

In [91]:
data.sort_values('나이') #나이를 기준으로 오름차순 정렬

나이   성별
0  20    남
1  23    여
6  25    여
9  26  NaN
5  29    여
7  30    여
4  32    여
8  32    남
3  38    여
2  49    남

In [92]:
data.sort_values('나이',ascending=False) #나이 기준으로 내림차순 정렬

나이   성별
2  49    남
3  38    여
4  32    여
8  32    남
7  30    여
5  29    여
9  26  NaN
6  25    여
1  23    여
0  20    남

In [93]:
data.sort_values(['나이','성별']) #나이와 성별 기준으로 오름차순 정렬

나이   성별
0  20    남
1  23    여
6  25    여
9  26  NaN
5  29    여
7  30    여
8  32    남
4  32    여
3  38    여
2  49    남

In [94]:
data

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [95]:
data['성별2']=data['성별'].fillna('남') #결측치를 남으로 바꾸기

In [96]:
data

나이   성별 성별2
0  20    남   남
1  23    여   여
2  49    남   남
3  38    여   여
4  32    여   여
5  29    여   여
6  25    여   여
7  30    여   여
8  32    남   남
9  26  NaN   남

In [99]:
data

나이   성별 성별2
0  20    남   남
1  23    여   여
2  49    남   남
3  38    여   여
4  32    여   여
5  29    여   여
6  25    여   여
7  30    여   여
8  32    남   남
9  26  NaN   남

In [97]:
data2 = data.dropna() #결측치 삭제
data2

나이 성별 성별2
0  20  남   남
1  23  여   여
2  49  남   남
3  38  여   여
4  32  여   여
5  29  여   여
6  25  여   여
7  30  여   여
8  32  남   남

In [98]:
data.head()

나이 성별 성별2
0  20  남   남
1  23  여   여
2  49  남   남
3  38  여   여
4  32  여   여

In [100]:
data.drop(index=[0,2,4,6,8]) #data 변수에서 0,2,4,6,8행을 삭제하기

나이   성별 성별2
1  23    여   여
3  38    여   여
5  29    여   여
7  30    여   여
9  26  NaN   남

In [102]:
data.drop(columns=['성별','성별2']) #성별 열 삭제하기

나이
0  20
1  23
2  49
3  38
4  32
5  29
6  25
7  30
8  32
9  26

In [103]:
# 성별 데이터에서 여는 F로 남은 M로 교체하기
# 기존 성별 데이터와 비교를 위해서 성별2 열 만들기

data['성별2'] = data['성별'].replace('여','F').replace('남','M')

In [104]:
data

나이   성별  성별2
0  20    남    M
1  23    여    F
2  49    남    M
3  38    여    F
4  32    여    F
5  29    여    F
6  25    여    F
7  30    여    F
8  32    남    M
9  26  NaN  NaN